                <!-- Footer START -->
                <footer class="footer">
                <p style="margin-top:50px;">   PLEASE READ THESE IMPORTANT LEGAL NOTICES AND DISCLOSURES</p>

<p>NONE OF THE INFORMATION DISPLAYED ON OR DOWNLOADABLE FROM WWW.FORGEGLOBAL.COM (THE “WEBSITE”) REPRESENTS AN OFFER TO BUY OR SELL OR A SOLICITATION OF AN OFFER TO BUY OR SELL ANY SECURITY, NOR DOES IT CONSTITUTE AN OFFER TO PROVIDE INVESTMENT ADVICE OR SERVICE. REGISTERED REPRESENTATIVES OF FORGE SECURITIES LLC DO NOT (1) ADVISE ANY MEMBER ON THE MERITS OR ADVISABILITY OF A PARTICULAR INVESTMENT OR TRANSACTION, OR (2) ASSIST IN THE DETERMINATION OF FAIR VALUE OF ANY SECURITY OR INVESTMENT, OR (3) PROVIDE LEGAL, TAX OR TRANSACTIONAL ADVISORY SERVICES.

ANY SECURITIES OFFERED ARE OFFERED THROUGH FORGE SECURITIES LLC, MEMBER FINRA/ SIPC. FORGE SECURITIES LLC AND FORGE GLOBAL ADVISORS LLC, AN INVESTMENT ADVISOR REGISTERED WITH THE SECURITIES AND EXCHANGE COMMISSION, ARE WHOLLY OWNED SUBSIDIARIES OF FORGE GLOBAL, INC. CERTAIN AFFILIATES OF THESE ENTITIES MAY ACT AS PRINCIPAL IN SUCH TRANSACTIONS.</p>

<p>ANY INFORMATION RELATING TO FULLY DILUTED SHARES OUTSTANDING OR OTHER COMPANY RELATED FINANCING OR CAPITALIZATION INFORMATION ARE ESTIMATES ONLY AND SHOULD BE INDEPENDENTLY VERIFIED BY EACH USER IN CONNECTION WITH ANY INVESTMENT DECISION.

ALL INVESTMENT OPPORTUNITIES ARE BASED ON INDICATED INTEREST FROM SELLERS AND WILL NEED TO BE CONFIRMED. ALL OPPORTUNITY SIZE AND PRICE-PER-SHARE FIGURES DO NOT INCLUDE TRANSACTION FEES OR FEES CHARGED BY FORGE SECURITIES LLC OR FORGE GLOBAL ADVISORS LLC.</p>

<p>INVESTING IN PRIVATE COMPANY SECURITIES IS NOT SUITABLE FOR ALL INVESTORS. AN INVESTMENT IN PRIVATE COMPANY SECURITIES IS HIGHLY SPECULATIVE AND INVOLVES A HIGH DEGREE OF RISK AND SHOULD ONLY BE CONSIDERED A LONG-TERM INVESTMENT. YOU MUST BE PREPARED TO WITHSTAND A TOTAL LOSS OF YOUR INVESTMENT. PRIVATE COMPANY SECURITIES ARE ALSO HIGHLY ILLIQUID AND THERE IS NO GUARANTEE THAT A MARKET WILL DEVELOP FOR SUCH SECURITIES. EACH INVESTMENT ALSO CARRIES ITS OWN SPECIFIC RISKS AND YOU SHOULD COMPLETE YOUR OWN INDEPENDENT DUE DILIGENCE REGARDING THE INVESTMENT, INCLUDING OBTAINING ADDITIONAL INFORMATION ABOUT THE COMPANY, OPINIONS, FINANCIAL PROJECTIONS AND LEGAL OR OTHER INVESTMENT ADVICE. ACCORDINGLY, INVESTING IN PRIVATE COMPANY SECURITIES IS APPROPRIATE ONLY FOR THOSE INVESTORS WHO CAN TOLERATE A HIGH DEGREE OF RISK AND DO NOT REQUIRE A LIQUID INVESTMENT. INHERENT, ACTUAL OR POTENTIAL CONFLICTS OF INTEREST MAY EXIST BETWEEN YOU AND FORGE GLOBAL.
            </p> 

            <p>FORGE DATA, LLC (“FORGE DATA”) IS A FORGE SECURITIES AFFILIATE THAT DISTRIBUTES TO ITS CUSTOMERS CERTAIN DATA PRODUCTS CONCERNING SECURITIES OF PRIVATE COMPANIES (“PRIVATE SECURITIES DATA”). FORGE DATA PROVIDES PRIVATE SECURITIES DATA TO ITS CUSTOMERS THROUGH ITS STAND-ALONE SUBSCRIPTION-BASED DIGITAL PLATFORM (THE “DATA PLATFORM”) THAT IS SEPARATE AND APART FROM THE FORGE SECURITIES PLATFORM AND THE SERVICES COVERED UNDER THIS AGREEMENT. PRIVATE SECURITIES DATA CONTAINS GENERAL PRIVATE COMPANY SECURITIES INFORMATION, AGGREGATED OR INDIVIDUAL HISTORICAL TRANSACTIONAL INFORMATION CONDUCTED ON THE ATS, HISTORICAL AND CURRENT AGGREGATED INDICATIONS OF INTEREST INFORMATION ON THE FORGE PLATFORM AND CURRENT INDIVIDUAL INDICATIONS OF INTEREST THROUGH AN IOI DATA FEED FROM FORGE SECURITIES. ALL PRIVATE SECURITIES DATA PROVIDED BY FORGE DATA IS ANONYMIZED. CONSUMERS SEEKING TO OBTAIN PRIVATE SECURITIES DATA ARE REQUIRED TO ENTER INTO A SEPARATE AGREEMENT BETWEEN THE CONSUMER AND FORGE DATA. DATA PLATFORM CONSUMERS MAY ALSO BE USERS OF THE SERVICES (“JOINT USERS”), MAY SUBMIT AND OTHERWISE HAVE ACCESS TO INDICATIONS OF INTEREST ON THE FORGE PLATFORM AND MAY ALSO BE CUSTOMERS OF FORGE SECURITIES AND ENGAGE IN THE PURCHASE AND SALE OF PRIVATE COMPANY SECURITIES THROUGH THE ATS. YOU UNDERSTAND THAT JOINT USERS, BY VIRTUE OF THEIR ACCESS TO THE DATA PLATFORM, WILL HAVE ACCESS TO PRIVATE SECURITIES DATA, WHICH INCLUDES SUBSTANTIAL AND ROBUST INFORMATION REGARDING PRIVATE COMPANY SECURITIES, INDICATIONS OF INTEREST, AND OTHER ELEMENTS OF THE SERVICE WHICH WILL NOT BE AVAILABLE TO USERS OF THE SERVICE THAT DO NOT SUBSCRIBE TO THE DATA PLATFORM.

BY USING THE WEBSITE OR THE INFORMATION, TOOLS, FEATURES OR FUNCTIONALITY PROVIDED ON THE WEBSITE AND BY FORGE GLOBAL CONSTITUTES ACCEPTANCE OF THE FORGE GLOBAL TERMS OF USE, PRIVACY POLICY, AND OTHER IMPORTANT DISCLOSURES.</p>

                </footer>
                <!-- Footer END -->

            </div>
            <!-- Page Container END -->
        </div>
    </div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>



<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
 <script src="https://cdn.datatables.net/buttons/2.0.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.print.min.js"></script>

    <!-- Core Vendors JS -->
    <script src="{{asset('asse/js/vendors.min.js')}}"></script>

    <!-- page js -->
    <script src="{{asset('asse/vendors/chartjs/Chart.min.js')}}"></script>
    <script src="{{asset('asse/js/pages/dashboard-crm.js')}}"></script>
    <script src="{{asset('asse/vendors/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('asse/vendors/datatables/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{asset('asse/js/pages/e-commerce-order-list.js')}}"></script>




    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
    <script src="{{asset('asse/vendors/select2/select2.min.js')}}"></script>
    <script src="{{asset('asse/vendors/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="https://cdn.datatables.net/scroller/2.0.2/js/dataTables.scroller.min.js" ></script>
    <script src="{{asset('asse/vendors/datatables/dataTables.bootstrap.min.js')}}"></script>





    >
    <!--<script src="/assets/DataTables/datatables.min.js" ></script>-->
    <script src="{{asset('asse/vendors/chartjs/Chart.min.js')}}"></script>

    <!-- Core JS -->
    <script src="{{asset('asse/js/app.min.js')}}"></script>

</body>

</html>
